### ISSUE TITLE
Getters / attributes not serialized

### ISSUE THREAD

**Issue by t3h2mas** [talyssonoc/structure#136]
It would be convenient for getters and or attributes to be serializable via `#toJSON` or `JSON.stringify`

```
cont Thing = attributes({
    name: String
})(
    class Thing {
        get wild() {
            return 'wild thing'
        }
        get name() {
            return `Thing { ${this.get('name')} }`
        }
    }
)
```

Currently #toJSON would return an empty object, same with `JSON.stringify`

Could one or both of the getter or attribute be added to the sterilization results?

**Comment by talyssonoc** [comment]
Hello, @t3h2mas. I'm not sure what you mean, running your example able like this:

```js
const Thing = attributes({
      name: String,
    })(
      class Thing {
        get wild() {
          return 'wild thing';
        }
        get name() {
          return `Thing { ${this.get('name')} }`;
        }
      }
    );

    const thing = new Thing({ name: 'abc' });

    console.log(thing.toJSON());
```

it shows `{ name: 'Thing { abc }' }` for me.

**Comment by t3h2mas** [comment]
I must have been using v1 or messed up my trial code.

Non-issue, sorry for the confusion.
