### ISSUE TITLE
Number coercion

### ISSUE THREAD

**Issue by kissmygritts** [talyssonoc/structure#40]
I don't really understand why Number coercion will coerce empty strings in a number field to 0 rather than `null` or `undefined`? Below is a link to an example.

https://runkit.com/kissmygritts/59a762562014bb00124e5bb5

**Comment by talyssonoc** [comment]
Coercion of empty string is done by this line https://github.com/talyssonoc/structure/blob/master/src/coercion/number.js#L11, it's a JavaScript design decision so I just kept it compliant. So if you simply run `Number('')` in the console you'll see that it coerces to `0` as well.

**Comment by kissmygritts** [comment]
Thank you for explaining.
