### ISSUE TITLE
Module not found: Can't resolve 'dns' in 'node_modules/isemail/lib'

### ISSUE THREAD

**Issue by sgonzaloc** [talyssonoc/structure#41]
I just installed this repository with **yarn** and I received this message when I run it with "_npm start_"

```
./node_modules/isemail/lib/index.js
Module not found: Can't resolve 'dns' in '.../node_modules/isemail/lib'
```

My package.json is like this

> {
...
  "dependencies": {
    "@mapbox/mapbox-gl-draw": "https://github.com/mlepinay/mapbox-gl-draw-es5.git",
    "ably": "^1.0.5",
    "autosuggest-highlight": "^3.1.0",
    "axios": "^0.16.2",
    "babel-polyfill": "^6.26.0",
    "bluebird": "^3.5.0",
    "classnames": "^2.2.5",
    "deck.gl": "^4.0.6",
    "deepmerge": "^1.5.0",
    "es6-enum": "^1.1.0",
    "eslint-plugin-compat": "^2.0.1",
    "external-editor": "^2.0.4",
    "fast-deep-equal": "^1.0.0",
    "has-flag": "^2.0.0",
    "immutable": "^3.8.1",
    "is-promise": "^2.1.0",
    "js-base64": "^2.1.9",
    "json-schema-traverse": "^0.3.1",
    "klaw": "^2.0.0",
    "localforage": "^1.5.0",
    "lodash": "^4.17.4",
    "luma.gl": "^3.0.2",
    "mapbox-gl": "^0.38.0",
    "material-ui": "1.0.0-beta.6",
    "material-ui-icons": "1.0.0-beta.4",
    "material-ui-password-field": "^1.3.0",
    "mimic-fn": "^1.1.0",
    "moment": "^2.18.1",
    "p-map": "^1.1.1",
    "promise-waterfall": "^0.1.0",
    "promise.waterfall": "^3.2.0",
    "prop-types": "^15.5.10",
    "query-string": "^5.0.0",
    "r-dom": "^2.3.2",
    "react": "^15.6.1",
    "react-autosuggest": "^9.3.1",
    "react-custom-scrollbars": "^4.1.2",
    "react-dimensions": "^1.3.0",
    "react-dom": "^15.6.1",
    "react-dropzone": "^3.13.3",
    "react-filter-box": "^2.0.0",
    "react-hotkeys": "^0.10.0",
    "react-localization": "0.0.17",
    "react-map-gl": "^2.0.3",
    "react-mapbox-autocomplete": "^0.2.3",
    "react-mapbox-gl": "^2.5.3",
    "react-mapbox-gl-draw": "^1.0.3",
    "react-modal": "^2.2.1",
    "react-progress-bar-plus": "^1.3.1",
    "react-redux": "^5.0.5",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^4.0.8",
    "react-shortcut": "^1.0.6",
    "react-shortcuts": "^1.5.0",
    "react-sortable-hoc": "^0.6.5",
    "react-stack-grid": "^0.2.2",
    "react-stepper-horizontal": "^1.0.9",
    "react-tap-event-plugin": "^2.0.1",
    "react-typeahead-component": "^0.9.0",
    "reactjs-localstorage": "0.0.5",
    "recharts": "^1.0.0-alpha.1",
    "redux": "^3.7.1",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0",
    "rx-lite-aggregates": "^4.0.8",
    "socket.io-client": "^2.0.3",
    "socket.io-react": "^1.2.0",
    "string-similarity": "^1.2.0",
    "structure": "^1.2.1",
    "superagent": "^3.5.2",
    "typeface-roboto": "0.0.29",
    "uuid": "^3.1.0",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "react-scripts": "1.0.14"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

**Comment by talyssonoc** [comment]
Based on your other dependencies I see you're using Structure for frontend development. For these cases you need to alias `joi` to `joi-browser`: https://github.com/talyssonoc/structure#browser
