### ISSUE TITLE
Schema subclass loses validate method

### ISSUE THREAD

**Issue by jeremyruppel** [talyssonoc/structure#48]
Currently, if you try to subclass a structure with another structure, you get an error when you call `.validate()` on the subclass.

```js
const { attributes } = require('structure')
const Foo = attributes({})(class Foo {})
const Bar = attributes({})(class Bar extends Foo {})
const bar = new Bar
bar.validate()

/* throws:
  const errors = validation.validate(data);
                            ^

TypeError: Cannot read property 'validate' of undefined
*/
```

The problem is [this bit](https://github.com/talyssonoc/structure/blob/master/src/attributes/decorator.js#L33-L35), where all enumerable properties get assigned from `schema` and `WrapperClass[SCHEMA]` to a new object and non-enumerable properties get left behind. 

I can think of two ways to fix this:

1. Make `VALIDATE` enumerable [here](https://github.com/talyssonoc/structure/blob/master/src/schema/normalization.js#L14-L16), which will make `Object.assign` do the right thing. The only thing I'd be concerned about is now [`Object.keys`](https://github.com/talyssonoc/structure/blob/master/src/attributes/decorator.js#L49-L51) would pick up `VALIDATE` as well and place it on the instance where it probably shouldn't be.
2. Move the [`Schema.normalize`](https://github.com/talyssonoc/structure/blob/master/src/attributes/decorator.js#L31) call down a few lines so it takes effect after the schema extension. 

I'm happy to submit a patch for either approach, just let me know what you think would be best. Thanks!

**Comment by talyssonoc** [comment]
Hello @jeremyruppel, I like the second approach! The contribution will be appreciated!

**Comment by jeremyruppel** [comment]
Right on, I'll send up the PR today. Thanks @talyssonoc!
