### ISSUE TITLE
Get other attribute value from a function called within a default value

### ISSUE THREAD

**Issue by joinnusdev** [talyssonoc/structure#51]
As I saw in the documentation, the default value can be filled with a function, but I can't figure it out how to get a value from another attribute in that function.

I am trying to do something like this:

```
const { attributes } = require('structure');

const Foo = attributes({
  paymentTotal: Number,
  quantity: Number,
  finalPrice: {
    type: Number,
    default: (i) => i.calcFinalPrice(),
  },
})(class Foo {
  calcFinalPrice() {
    return this.paymentTotal / this.quantity;
  }
});

module.exports = Foot;
```

But this.paymentTotal is undefined. If I understood correctly, this functions gets called when all other fields are filled right?. 

Version: 1.2.1
Over node 8.9.4

**Comment by wenderjean** [comment]
hey @joinnusdev,

So, not exactly, I was creating some cases here to reproduce this behavior and currently we are going through each attribute at the same time parsing each one separately and after all of them filled we set them to the instance.

**Comment by wenderjean** [comment]
@talyssonoc Can you close this one?

**Comment by talyssonoc** [comment]
Sure!
