### ISSUE TITLE
Empty String Converted to 0 and returns Valid

### ISSUE THREAD

**Issue by agstover** [talyssonoc/structure#59]
I'm creating a user. The entity looks like this:

```
const User = attributes({
  id: {
    type: Number,
    required: true,
    empty: false
  },
//// other attributes exist, but left out for brevity
})(class User {})
```
I'm creating a new User with an empty string as an id (for testing valid/invalid) by doing this:

```
        const user = new User({
          id:'',
        })
```
I would imagine that this would cause the test to fail since an empty string isn't a number and empty is false, but when I check the user ID after creating the user it's 0. Am I misunderstanding something about how to use this library?

**Comment by brunohkbx** [comment]
Hey @talyssonoc what do you think about this?
I think this is the expected coercion behavior of this primitive.

**Comment by talyssonoc** [comment]
This is JavaScript's default behavior, we don't opinionate about it. If you do `Number('')' you'll see JS will conver it to `0`. This is documented here https://structure.js.org/coercion/primitive-type-coercion
