### ISSUE TITLE
Support Map types with itemType

### ISSUE THREAD

**Issue by loweoj** [talyssonoc/structure#60]
It would be really useful to support Map types with itemType. Currently specifying an attribute as type Map results in "attribute.map is not a function" on attribute serialization. Is this something that could be added? If it's just a case of implementing a .map function for Map then that would be relatively trivial?

My use case is storing itemType's ID value as a key on Map.

Thanks!

**Comment by LeoGigliotti** [comment]
This would be an excellent feature. We are currently working with DynamoDB and we often bump into cases where we want objects with dynamic property naming. This is an excelent use case for saving dictionaries and/or hashtables.

Both JavaScript and DynamoDB supports this use scenario and it would be a great addition to structure.

**Comment by talyssonoc** [comment]
As discusses, we're gonna define the key and item type like this:

```js
{
  permissions: {
    type: Map,
    itemType: { key: String, value: Permission }
  }
}
```

**Comment by loweoj** [comment]
Where the value of `key` is a property on `Permission`? e.g.

``` javascript
  permissions: {
    type: Map,
    itemType: { key: 'permissionId', value: Permission }
  }
```
