### ISSUE TITLE
option to override property on validation

### ISSUE THREAD

**Issue by overflowz** [talyssonoc/structure#64]
Here's the case, imagine a schema, which requires e.g. `ID` to be required during `update` operation, but it is not required during `create` operation. Any ways to validate it somehow like this tho?

**Comment by talyssonoc** [comment]
How would you define what is the creation and what is the update scenario?

**Comment by overflowz** [comment]
The issue was created 2 years ago, I don't even remember what it is about 😅 Closing instead.

**Comment by talyssonoc** [comment]
Sorry for the long delay on that, I had to focus on some other stuff and I'm not trying to get active on the project again after we released v2.

**Comment by overflowz** [comment]
no worries man, keep up the good work! 👍
